# Generated by Django 5.1 on 2024-08-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resident",
            name="activities",
            field=models.ManyToManyField(
                blank=True, related_name="residents", to="api.activity"
            ),
        ),
    ]
